# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
		config.vm.box = "hashicorp/precise64"
		config.vm.box_download_insecure = true
		config.vm.network "public_network", ip: "172.0.0.103"
		config.vm.hostname = "jobo.com"
		#config.ssh.username = "vagrant"
		#config.ssh.password = "vagrant"
		#config.ssh.insert_key = true
		
		# Mysql listener
		config.vm.network "forwarded_port", guest: 3306, host: 3306, protocol: 'tcp'
		#config.vm.network "forwarded_port", guest: 3306, host: 3306, protocol: 'udp'
					
		# More box config
		config.vm.provider "virtualbox" do |vb|
		# Customize the amount of memory on the VM:
			vb.customize ["modifyvm", :id, "--memory","2048"]
		end
			
		config.vm.provision :shell, path: "bootstrap_mysql.sh"
		config.vm.synced_folder "./sync_folder/", "/vagrant"
end
