USE jobo;
DROP TABLE IF EXISTS jprofile;
CREATE TABLE jprofile (pfid INT AUTO_INCREMENT, fname VARCHAR(255), mname VARCHAR(255), lname VARCHAR(255), pname VARCHAR(255), uname VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(15), cell VARCHAR(15), adl1 VARCHAR(255), adl2 VARCHAR(255), suburb VARCHAR(25), city VARCHAR(25), region VARCHAR(25), country VARCHAR(15), postalcd VARCHAR(10), password VARCHAR(255) NOT NULL, tmstamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (pfid));

DROP TABLE IF EXISTS jentries;
CREATE TABLE jentries (eid INT AUTO_INCREMENT, pfid INT NOT NULL, jobtitle VARCHAR(50) NOT NULL, company VARCHAR(50), adwhere VARCHAR(50),addate DATE, cname1 VARCHAR(255), cphone1 VARCHAR(15), cemail1 VARCHAR(255), cname2 VARCHAR(255), cphone2 VARCHAR(15), cemail2 VARCHAR(255), cvsent TINYINT(1) UNSIGNED ZEROFILL, replyrcvd VARCHAR(25), intvwdates VARCHAR(25), followupdt DATE, followup TINYINT(1) UNSIGNED ZEROFILL, comments VARCHAR(255), tmstamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (eid), FOREIGN KEY (pfid) REFERENCES jprofile(pfid));
